version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/docker
  docker: circleci/docker@3.0.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - setup_remote_docker:
          # https://circleci.com/docs/guides/execution-managed/building-docker-images/
          version: docker24
          # https://circleci.com/docs/reference/glossary/#docker-layer-caching
          docker_layer_caching: true
      - attach_workspace:
          at: /home/circleci/project
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          chmod 755 ~/.docker
          chmod 644 ~/.docker/config.json
          if [ "${CIRCLE_BRANCH}" != "" ]; then export "GIT_BRANCH=${CIRCLE_BRANCH}";else export "GIT_BRANCH=${CIRCLE_TAG}";fi
          export "BUILD_VERSION=${GIT_BRANCH}"
          export "PROJECT_NAME=bpaotu"
          "./circleci-prodbuild.sh"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Bioplatforms
          filters:
            tags:
              only: /^\d+\.\d+(\.\d+)?(-\S*)?$/
            branches:
              ignore: /.*/
